//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ClienteTemperatura.ServicioClima {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://Clima/", ConfigurationName="ServicioClima.WsClima")]
    public interface WsClima {
        
        // CODEGEN: Se está generando un contrato de mensaje, ya que el nombre de elemento fecha del espacio de nombres  no está marcado para aceptar valores nil.
        [System.ServiceModel.OperationContractAttribute(Action="http://Clima/WsClima/getClimaPorcentajeRequest", ReplyAction="http://Clima/WsClima/getClimaPorcentajeResponse")]
        ClienteTemperatura.ServicioClima.getClimaPorcentajeResponse getClimaPorcentaje(ClienteTemperatura.ServicioClima.getClimaPorcentajeRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://Clima/WsClima/getClimaPorcentajeRequest", ReplyAction="http://Clima/WsClima/getClimaPorcentajeResponse")]
        System.Threading.Tasks.Task<ClienteTemperatura.ServicioClima.getClimaPorcentajeResponse> getClimaPorcentajeAsync(ClienteTemperatura.ServicioClima.getClimaPorcentajeRequest request);
        
        // CODEGEN: Se está generando un contrato de mensaje, ya que el nombre de elemento fecha del espacio de nombres  no está marcado para aceptar valores nil.
        [System.ServiceModel.OperationContractAttribute(Action="http://Clima/WsClima/getClimaTemperaturaRequest", ReplyAction="http://Clima/WsClima/getClimaTemperaturaResponse")]
        ClienteTemperatura.ServicioClima.getClimaTemperaturaResponse getClimaTemperatura(ClienteTemperatura.ServicioClima.getClimaTemperaturaRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://Clima/WsClima/getClimaTemperaturaRequest", ReplyAction="http://Clima/WsClima/getClimaTemperaturaResponse")]
        System.Threading.Tasks.Task<ClienteTemperatura.ServicioClima.getClimaTemperaturaResponse> getClimaTemperaturaAsync(ClienteTemperatura.ServicioClima.getClimaTemperaturaRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class getClimaPorcentajeRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="getClimaPorcentaje", Namespace="http://Clima/", Order=0)]
        public ClienteTemperatura.ServicioClima.getClimaPorcentajeRequestBody Body;
        
        public getClimaPorcentajeRequest() {
        }
        
        public getClimaPorcentajeRequest(ClienteTemperatura.ServicioClima.getClimaPorcentajeRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="")]
    public partial class getClimaPorcentajeRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string fecha;
        
        public getClimaPorcentajeRequestBody() {
        }
        
        public getClimaPorcentajeRequestBody(string fecha) {
            this.fecha = fecha;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class getClimaPorcentajeResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="getClimaPorcentajeResponse", Namespace="http://Clima/", Order=0)]
        public ClienteTemperatura.ServicioClima.getClimaPorcentajeResponseBody Body;
        
        public getClimaPorcentajeResponse() {
        }
        
        public getClimaPorcentajeResponse(ClienteTemperatura.ServicioClima.getClimaPorcentajeResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="")]
    public partial class getClimaPorcentajeResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string @return;
        
        public getClimaPorcentajeResponseBody() {
        }
        
        public getClimaPorcentajeResponseBody(string @return) {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class getClimaTemperaturaRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="getClimaTemperatura", Namespace="http://Clima/", Order=0)]
        public ClienteTemperatura.ServicioClima.getClimaTemperaturaRequestBody Body;
        
        public getClimaTemperaturaRequest() {
        }
        
        public getClimaTemperaturaRequest(ClienteTemperatura.ServicioClima.getClimaTemperaturaRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="")]
    public partial class getClimaTemperaturaRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string fecha;
        
        public getClimaTemperaturaRequestBody() {
        }
        
        public getClimaTemperaturaRequestBody(string fecha) {
            this.fecha = fecha;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class getClimaTemperaturaResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="getClimaTemperaturaResponse", Namespace="http://Clima/", Order=0)]
        public ClienteTemperatura.ServicioClima.getClimaTemperaturaResponseBody Body;
        
        public getClimaTemperaturaResponse() {
        }
        
        public getClimaTemperaturaResponse(ClienteTemperatura.ServicioClima.getClimaTemperaturaResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="")]
    public partial class getClimaTemperaturaResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string @return;
        
        public getClimaTemperaturaResponseBody() {
        }
        
        public getClimaTemperaturaResponseBody(string @return) {
            this.@return = @return;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface WsClimaChannel : ClienteTemperatura.ServicioClima.WsClima, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class WsClimaClient : System.ServiceModel.ClientBase<ClienteTemperatura.ServicioClima.WsClima>, ClienteTemperatura.ServicioClima.WsClima {
        
        public WsClimaClient() {
        }
        
        public WsClimaClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public WsClimaClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public WsClimaClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public WsClimaClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        ClienteTemperatura.ServicioClima.getClimaPorcentajeResponse ClienteTemperatura.ServicioClima.WsClima.getClimaPorcentaje(ClienteTemperatura.ServicioClima.getClimaPorcentajeRequest request) {
            return base.Channel.getClimaPorcentaje(request);
        }
        
        public string getClimaPorcentaje(string fecha) {
            ClienteTemperatura.ServicioClima.getClimaPorcentajeRequest inValue = new ClienteTemperatura.ServicioClima.getClimaPorcentajeRequest();
            inValue.Body = new ClienteTemperatura.ServicioClima.getClimaPorcentajeRequestBody();
            inValue.Body.fecha = fecha;
            ClienteTemperatura.ServicioClima.getClimaPorcentajeResponse retVal = ((ClienteTemperatura.ServicioClima.WsClima)(this)).getClimaPorcentaje(inValue);
            return retVal.Body.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<ClienteTemperatura.ServicioClima.getClimaPorcentajeResponse> ClienteTemperatura.ServicioClima.WsClima.getClimaPorcentajeAsync(ClienteTemperatura.ServicioClima.getClimaPorcentajeRequest request) {
            return base.Channel.getClimaPorcentajeAsync(request);
        }
        
        public System.Threading.Tasks.Task<ClienteTemperatura.ServicioClima.getClimaPorcentajeResponse> getClimaPorcentajeAsync(string fecha) {
            ClienteTemperatura.ServicioClima.getClimaPorcentajeRequest inValue = new ClienteTemperatura.ServicioClima.getClimaPorcentajeRequest();
            inValue.Body = new ClienteTemperatura.ServicioClima.getClimaPorcentajeRequestBody();
            inValue.Body.fecha = fecha;
            return ((ClienteTemperatura.ServicioClima.WsClima)(this)).getClimaPorcentajeAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        ClienteTemperatura.ServicioClima.getClimaTemperaturaResponse ClienteTemperatura.ServicioClima.WsClima.getClimaTemperatura(ClienteTemperatura.ServicioClima.getClimaTemperaturaRequest request) {
            return base.Channel.getClimaTemperatura(request);
        }
        
        public string getClimaTemperatura(string fecha) {
            ClienteTemperatura.ServicioClima.getClimaTemperaturaRequest inValue = new ClienteTemperatura.ServicioClima.getClimaTemperaturaRequest();
            inValue.Body = new ClienteTemperatura.ServicioClima.getClimaTemperaturaRequestBody();
            inValue.Body.fecha = fecha;
            ClienteTemperatura.ServicioClima.getClimaTemperaturaResponse retVal = ((ClienteTemperatura.ServicioClima.WsClima)(this)).getClimaTemperatura(inValue);
            return retVal.Body.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<ClienteTemperatura.ServicioClima.getClimaTemperaturaResponse> ClienteTemperatura.ServicioClima.WsClima.getClimaTemperaturaAsync(ClienteTemperatura.ServicioClima.getClimaTemperaturaRequest request) {
            return base.Channel.getClimaTemperaturaAsync(request);
        }
        
        public System.Threading.Tasks.Task<ClienteTemperatura.ServicioClima.getClimaTemperaturaResponse> getClimaTemperaturaAsync(string fecha) {
            ClienteTemperatura.ServicioClima.getClimaTemperaturaRequest inValue = new ClienteTemperatura.ServicioClima.getClimaTemperaturaRequest();
            inValue.Body = new ClienteTemperatura.ServicioClima.getClimaTemperaturaRequestBody();
            inValue.Body.fecha = fecha;
            return ((ClienteTemperatura.ServicioClima.WsClima)(this)).getClimaTemperaturaAsync(inValue);
        }
    }
}
