//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OperacionCliente.ServicioOp {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://operaciones/", ConfigurationName="ServicioOp.Operaciones")]
    public interface Operaciones {
        
        // CODEGEN: Se está generando un contrato de mensaje, ya que el nombre de elemento name del espacio de nombres  no está marcado para aceptar valores nil.
        [System.ServiceModel.OperationContractAttribute(Action="http://operaciones/Operaciones/helloRequest", ReplyAction="http://operaciones/Operaciones/helloResponse")]
        OperacionCliente.ServicioOp.helloResponse hello(OperacionCliente.ServicioOp.helloRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://operaciones/Operaciones/helloRequest", ReplyAction="http://operaciones/Operaciones/helloResponse")]
        System.Threading.Tasks.Task<OperacionCliente.ServicioOp.helloResponse> helloAsync(OperacionCliente.ServicioOp.helloRequest request);
        
        // CODEGEN: Se está generando un contrato de mensaje, ya que el espacio de nombres de partes de mensaje () no coincide con el valor predeterminado (http://operaciones/).
        [System.ServiceModel.OperationContractAttribute(Action="http://operaciones/Operaciones/sumaRequest", ReplyAction="http://operaciones/Operaciones/sumaResponse")]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        OperacionCliente.ServicioOp.sumaResponse suma(OperacionCliente.ServicioOp.sumaRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://operaciones/Operaciones/sumaRequest", ReplyAction="http://operaciones/Operaciones/sumaResponse")]
        System.Threading.Tasks.Task<OperacionCliente.ServicioOp.sumaResponse> sumaAsync(OperacionCliente.ServicioOp.sumaRequest request);
        
        // CODEGEN: Se está generando un contrato de mensaje, ya que el espacio de nombres de partes de mensaje () no coincide con el valor predeterminado (http://operaciones/).
        [System.ServiceModel.OperationContractAttribute(Action="http://operaciones/Operaciones/restarRequest", ReplyAction="http://operaciones/Operaciones/restarResponse")]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        OperacionCliente.ServicioOp.restarResponse restar(OperacionCliente.ServicioOp.restarRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://operaciones/Operaciones/restarRequest", ReplyAction="http://operaciones/Operaciones/restarResponse")]
        System.Threading.Tasks.Task<OperacionCliente.ServicioOp.restarResponse> restarAsync(OperacionCliente.ServicioOp.restarRequest request);
        
        // CODEGEN: Se está generando un contrato de mensaje, ya que el espacio de nombres de partes de mensaje () no coincide con el valor predeterminado (http://operaciones/).
        [System.ServiceModel.OperationContractAttribute(Action="http://operaciones/Operaciones/multiplicacionRequest", ReplyAction="http://operaciones/Operaciones/multiplicacionResponse")]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        OperacionCliente.ServicioOp.multiplicacionResponse multiplicacion(OperacionCliente.ServicioOp.multiplicacionRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://operaciones/Operaciones/multiplicacionRequest", ReplyAction="http://operaciones/Operaciones/multiplicacionResponse")]
        System.Threading.Tasks.Task<OperacionCliente.ServicioOp.multiplicacionResponse> multiplicacionAsync(OperacionCliente.ServicioOp.multiplicacionRequest request);
        
        // CODEGEN: Se está generando un contrato de mensaje, ya que el espacio de nombres de partes de mensaje () no coincide con el valor predeterminado (http://operaciones/).
        [System.ServiceModel.OperationContractAttribute(Action="http://operaciones/Operaciones/divisionRequest", ReplyAction="http://operaciones/Operaciones/divisionResponse")]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        OperacionCliente.ServicioOp.divisionResponse division(OperacionCliente.ServicioOp.divisionRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://operaciones/Operaciones/divisionRequest", ReplyAction="http://operaciones/Operaciones/divisionResponse")]
        System.Threading.Tasks.Task<OperacionCliente.ServicioOp.divisionResponse> divisionAsync(OperacionCliente.ServicioOp.divisionRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class helloRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="hello", Namespace="http://operaciones/", Order=0)]
        public OperacionCliente.ServicioOp.helloRequestBody Body;
        
        public helloRequest() {
        }
        
        public helloRequest(OperacionCliente.ServicioOp.helloRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="")]
    public partial class helloRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string name;
        
        public helloRequestBody() {
        }
        
        public helloRequestBody(string name) {
            this.name = name;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class helloResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="helloResponse", Namespace="http://operaciones/", Order=0)]
        public OperacionCliente.ServicioOp.helloResponseBody Body;
        
        public helloResponse() {
        }
        
        public helloResponse(OperacionCliente.ServicioOp.helloResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="")]
    public partial class helloResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string @return;
        
        public helloResponseBody() {
        }
        
        public helloResponseBody(string @return) {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="suma", WrapperNamespace="http://operaciones/", IsWrapped=true)]
    public partial class sumaRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=0)]
        public int num1;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=1)]
        public int num2;
        
        public sumaRequest() {
        }
        
        public sumaRequest(int num1, int num2) {
            this.num1 = num1;
            this.num2 = num2;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="sumaResponse", WrapperNamespace="http://operaciones/", IsWrapped=true)]
    public partial class sumaResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=0)]
        public int @return;
        
        public sumaResponse() {
        }
        
        public sumaResponse(int @return) {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="restar", WrapperNamespace="http://operaciones/", IsWrapped=true)]
    public partial class restarRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=0)]
        public int num1;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=1)]
        public int num2;
        
        public restarRequest() {
        }
        
        public restarRequest(int num1, int num2) {
            this.num1 = num1;
            this.num2 = num2;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="restarResponse", WrapperNamespace="http://operaciones/", IsWrapped=true)]
    public partial class restarResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=0)]
        public int @return;
        
        public restarResponse() {
        }
        
        public restarResponse(int @return) {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="multiplicacion", WrapperNamespace="http://operaciones/", IsWrapped=true)]
    public partial class multiplicacionRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=0)]
        public int num1;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=1)]
        public int num2;
        
        public multiplicacionRequest() {
        }
        
        public multiplicacionRequest(int num1, int num2) {
            this.num1 = num1;
            this.num2 = num2;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="multiplicacionResponse", WrapperNamespace="http://operaciones/", IsWrapped=true)]
    public partial class multiplicacionResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=0)]
        public int @return;
        
        public multiplicacionResponse() {
        }
        
        public multiplicacionResponse(int @return) {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="division", WrapperNamespace="http://operaciones/", IsWrapped=true)]
    public partial class divisionRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=0)]
        public int num1;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=1)]
        public int num2;
        
        public divisionRequest() {
        }
        
        public divisionRequest(int num1, int num2) {
            this.num1 = num1;
            this.num2 = num2;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="divisionResponse", WrapperNamespace="http://operaciones/", IsWrapped=true)]
    public partial class divisionResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=0)]
        public int @return;
        
        public divisionResponse() {
        }
        
        public divisionResponse(int @return) {
            this.@return = @return;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface OperacionesChannel : OperacionCliente.ServicioOp.Operaciones, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class OperacionesClient : System.ServiceModel.ClientBase<OperacionCliente.ServicioOp.Operaciones>, OperacionCliente.ServicioOp.Operaciones {
        
        public OperacionesClient() {
        }
        
        public OperacionesClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public OperacionesClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public OperacionesClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public OperacionesClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        OperacionCliente.ServicioOp.helloResponse OperacionCliente.ServicioOp.Operaciones.hello(OperacionCliente.ServicioOp.helloRequest request) {
            return base.Channel.hello(request);
        }
        
        public string hello(string name) {
            OperacionCliente.ServicioOp.helloRequest inValue = new OperacionCliente.ServicioOp.helloRequest();
            inValue.Body = new OperacionCliente.ServicioOp.helloRequestBody();
            inValue.Body.name = name;
            OperacionCliente.ServicioOp.helloResponse retVal = ((OperacionCliente.ServicioOp.Operaciones)(this)).hello(inValue);
            return retVal.Body.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<OperacionCliente.ServicioOp.helloResponse> OperacionCliente.ServicioOp.Operaciones.helloAsync(OperacionCliente.ServicioOp.helloRequest request) {
            return base.Channel.helloAsync(request);
        }
        
        public System.Threading.Tasks.Task<OperacionCliente.ServicioOp.helloResponse> helloAsync(string name) {
            OperacionCliente.ServicioOp.helloRequest inValue = new OperacionCliente.ServicioOp.helloRequest();
            inValue.Body = new OperacionCliente.ServicioOp.helloRequestBody();
            inValue.Body.name = name;
            return ((OperacionCliente.ServicioOp.Operaciones)(this)).helloAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        OperacionCliente.ServicioOp.sumaResponse OperacionCliente.ServicioOp.Operaciones.suma(OperacionCliente.ServicioOp.sumaRequest request) {
            return base.Channel.suma(request);
        }
        
        public int suma(int num1, int num2) {
            OperacionCliente.ServicioOp.sumaRequest inValue = new OperacionCliente.ServicioOp.sumaRequest();
            inValue.num1 = num1;
            inValue.num2 = num2;
            OperacionCliente.ServicioOp.sumaResponse retVal = ((OperacionCliente.ServicioOp.Operaciones)(this)).suma(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<OperacionCliente.ServicioOp.sumaResponse> OperacionCliente.ServicioOp.Operaciones.sumaAsync(OperacionCliente.ServicioOp.sumaRequest request) {
            return base.Channel.sumaAsync(request);
        }
        
        public System.Threading.Tasks.Task<OperacionCliente.ServicioOp.sumaResponse> sumaAsync(int num1, int num2) {
            OperacionCliente.ServicioOp.sumaRequest inValue = new OperacionCliente.ServicioOp.sumaRequest();
            inValue.num1 = num1;
            inValue.num2 = num2;
            return ((OperacionCliente.ServicioOp.Operaciones)(this)).sumaAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        OperacionCliente.ServicioOp.restarResponse OperacionCliente.ServicioOp.Operaciones.restar(OperacionCliente.ServicioOp.restarRequest request) {
            return base.Channel.restar(request);
        }
        
        public int restar(int num1, int num2) {
            OperacionCliente.ServicioOp.restarRequest inValue = new OperacionCliente.ServicioOp.restarRequest();
            inValue.num1 = num1;
            inValue.num2 = num2;
            OperacionCliente.ServicioOp.restarResponse retVal = ((OperacionCliente.ServicioOp.Operaciones)(this)).restar(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<OperacionCliente.ServicioOp.restarResponse> OperacionCliente.ServicioOp.Operaciones.restarAsync(OperacionCliente.ServicioOp.restarRequest request) {
            return base.Channel.restarAsync(request);
        }
        
        public System.Threading.Tasks.Task<OperacionCliente.ServicioOp.restarResponse> restarAsync(int num1, int num2) {
            OperacionCliente.ServicioOp.restarRequest inValue = new OperacionCliente.ServicioOp.restarRequest();
            inValue.num1 = num1;
            inValue.num2 = num2;
            return ((OperacionCliente.ServicioOp.Operaciones)(this)).restarAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        OperacionCliente.ServicioOp.multiplicacionResponse OperacionCliente.ServicioOp.Operaciones.multiplicacion(OperacionCliente.ServicioOp.multiplicacionRequest request) {
            return base.Channel.multiplicacion(request);
        }
        
        public int multiplicacion(int num1, int num2) {
            OperacionCliente.ServicioOp.multiplicacionRequest inValue = new OperacionCliente.ServicioOp.multiplicacionRequest();
            inValue.num1 = num1;
            inValue.num2 = num2;
            OperacionCliente.ServicioOp.multiplicacionResponse retVal = ((OperacionCliente.ServicioOp.Operaciones)(this)).multiplicacion(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<OperacionCliente.ServicioOp.multiplicacionResponse> OperacionCliente.ServicioOp.Operaciones.multiplicacionAsync(OperacionCliente.ServicioOp.multiplicacionRequest request) {
            return base.Channel.multiplicacionAsync(request);
        }
        
        public System.Threading.Tasks.Task<OperacionCliente.ServicioOp.multiplicacionResponse> multiplicacionAsync(int num1, int num2) {
            OperacionCliente.ServicioOp.multiplicacionRequest inValue = new OperacionCliente.ServicioOp.multiplicacionRequest();
            inValue.num1 = num1;
            inValue.num2 = num2;
            return ((OperacionCliente.ServicioOp.Operaciones)(this)).multiplicacionAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        OperacionCliente.ServicioOp.divisionResponse OperacionCliente.ServicioOp.Operaciones.division(OperacionCliente.ServicioOp.divisionRequest request) {
            return base.Channel.division(request);
        }
        
        public int division(int num1, int num2) {
            OperacionCliente.ServicioOp.divisionRequest inValue = new OperacionCliente.ServicioOp.divisionRequest();
            inValue.num1 = num1;
            inValue.num2 = num2;
            OperacionCliente.ServicioOp.divisionResponse retVal = ((OperacionCliente.ServicioOp.Operaciones)(this)).division(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<OperacionCliente.ServicioOp.divisionResponse> OperacionCliente.ServicioOp.Operaciones.divisionAsync(OperacionCliente.ServicioOp.divisionRequest request) {
            return base.Channel.divisionAsync(request);
        }
        
        public System.Threading.Tasks.Task<OperacionCliente.ServicioOp.divisionResponse> divisionAsync(int num1, int num2) {
            OperacionCliente.ServicioOp.divisionRequest inValue = new OperacionCliente.ServicioOp.divisionRequest();
            inValue.num1 = num1;
            inValue.num2 = num2;
            return ((OperacionCliente.ServicioOp.Operaciones)(this)).divisionAsync(inValue);
        }
    }
}
